from __future__ import annotations

import configparser
import json
from pathlib import Path
from typing import Any

from pydantic import ValidationError

from options_analytics.config import Config

CONFIG_FILENAME = "config.toml"
LEGACY_CONFIG_FILENAME = "config.ini"
CONFIG_VERSION = 1


def _toml_quote(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _prompt_text(prompt: str) -> str:
    return input(f"{prompt}\n> ").strip()


def _prompt_non_empty(prompt: str) -> str:
    while True:
        value = _prompt_text(prompt)
        if value:
            return value
        print("This field is required.")


def _prompt_yes_no(question: str) -> bool:
    while True:
        normalized = _prompt_text(f"{question} [y/n]").lower()
        if normalized in {"y", "yes"}:
            return True
        if normalized in {"n", "no"}:
            return False
        print("Please enter y/yes or n/no.")


def _collect_accounts() -> list[dict[str, str]]:
    accounts: list[dict[str, str]] = []
    account_index = 1
    while True:
        print(f"\nAccount #{account_index}")
        label = _prompt_non_empty("Account label:")
        account_id = _prompt_non_empty("Account ID:")
        accounts.append({"label": label, "id": account_id})
        if not _prompt_yes_no("Add another account?"):
            break
        account_index += 1
    return accounts


def _collect_config_data() -> dict[str, Any]:
    print("Config setup wizard")
    print("This writes config.toml in the current working directory.")

    api_key = _prompt_non_empty("E*TRADE API key:")
    api_secret = _prompt_non_empty("E*TRADE API secret:")
    print("\nE*TRADE account setup")
    accounts = _collect_accounts()

    return {
        "version": CONFIG_VERSION,
        "etrade": {
            "accounts": accounts,
            "key": {"api": api_key, "secret": api_secret},
        },
    }


def _format_validation_errors(error: ValidationError) -> list[str]:
    lines = ["Validation failed. config.toml was not written.", ""]
    for issue in error.errors():
        location = ".".join(str(part) for part in issue["loc"])
        lines.append(f"- {location}: {issue['msg']}")
    return lines


def _render_toml(data: dict[str, Any]) -> str:
    lines = [
        "# Generated by setup_config.py.",
        "# Review values before running analytics scripts.",
        "",
        f"version = {data['version']}",
        "",
        "[etrade]",
        "",
        "# Add one [[etrade.accounts]] block for each E*TRADE account.",
    ]

    accounts: list[dict[str, str]] = data["etrade"]["accounts"]
    for account in accounts:
        lines.extend(
            [
                "[[etrade.accounts]]",
                "# Display label for this account.",
                f"label = {_toml_quote(account['label'])}",
                "# E*TRADE account ID for this account.",
                f"id = {_toml_quote(account['id'])}",
                "",
            ]
        )

    lines.extend(
        [
            "[etrade.key]",
            "# E*TRADE API consumer key from the developer portal.",
            f"api = {_toml_quote(data['etrade']['key']['api'])}",
            "# E*TRADE API consumer secret from the developer portal.",
            f"secret = {_toml_quote(data['etrade']['key']['secret'])}",
        ]
    )
    return "\n".join(lines).rstrip() + "\n"


def _confirm_overwrite(config_path: Path) -> bool:
    if not config_path.exists():
        return True

    print(f"Found existing file: {config_path}")
    overwrite = _prompt_yes_no("Overwrite existing config.toml?")
    if not overwrite:
        print("No changes were made.")
        return False
    return True


def _ensure_required_data(data: dict[str, Any]) -> None:
    if data.get("version") != CONFIG_VERSION:
        raise ValueError(f"Only config version {CONFIG_VERSION} is supported.")

    etrade = data.get("etrade")
    if not isinstance(etrade, dict):
        raise ValueError("Missing required [etrade] configuration.")

    accounts = etrade.get("accounts")
    if not isinstance(accounts, list) or not accounts:
        raise ValueError("At least one E*TRADE account is required.")


def _convert_legacy_ini(legacy_path: Path) -> dict[str, Any]:
    parser = configparser.ConfigParser()
    read_files = parser.read(legacy_path)
    if not read_files:
        raise ValueError(f"Unable to read {legacy_path}.")

    defaults = parser["DEFAULT"]
    consumer_key = defaults.get("CONSUMER_KEY", "").strip()
    consumer_secret = defaults.get("CONSUMER_SECRET", "").strip()
    account_list_raw = defaults.get("ACCOUNT_LIST", "").strip()

    if not consumer_key:
        raise ValueError("CONSUMER_KEY is missing or empty.")
    if not consumer_secret:
        raise ValueError("CONSUMER_SECRET is missing or empty.")
    if not account_list_raw:
        raise ValueError("ACCOUNT_LIST is missing or empty.")

    try:
        account_list = json.loads(account_list_raw)
    except json.JSONDecodeError as exc:
        raise ValueError(f"ACCOUNT_LIST is not valid JSON: {exc}") from exc

    if not isinstance(account_list, list):
        raise ValueError("ACCOUNT_LIST must be a JSON array.")

    accounts: list[dict[str, str]] = []
    for index, account in enumerate(account_list, start=1):
        if not isinstance(account, dict):
            raise ValueError(f"ACCOUNT_LIST item #{index} must be an object.")

        account_id = str(account.get("id", "")).strip()
        label = str(account.get("label", account.get("name", ""))).strip()

        if not account_id:
            raise ValueError(f"ACCOUNT_LIST item #{index} is missing id.")
        if not label:
            raise ValueError(
                f"ACCOUNT_LIST item #{index} is missing label or name."
            )

        accounts.append({"id": account_id, "label": label})

    return {
        "version": CONFIG_VERSION,
        "etrade": {
            "accounts": accounts,
            "key": {
                "api": consumer_key,
                "secret": consumer_secret,
            },
        },
    }


def _validate_data(data: dict[str, Any]) -> None:
    _ensure_required_data(data)
    Config.model_validate(data)


def _write_and_verify(data: dict[str, Any], config_path: Path) -> None:
    config_path.write_text(_render_toml(data), encoding="utf-8")
    Config.from_file(str(config_path))


def main() -> int:
    try:
        config_path = Path.cwd() / CONFIG_FILENAME
        legacy_path = Path.cwd() / LEGACY_CONFIG_FILENAME

        if legacy_path.exists():
            print(f"Found legacy file: {legacy_path}")
            should_convert = _prompt_yes_no(
                "Convert config.ini to config.toml and delete config.ini "
                "after successful conversion?"
            )
            if should_convert:
                if not _confirm_overwrite(config_path):
                    return 0

                try:
                    data = _convert_legacy_ini(legacy_path)
                    _validate_data(data)
                except ValidationError as exc:
                    for line in _format_validation_errors(exc):
                        print(line)
                    return 1
                except ValueError as exc:
                    print(f"Unable to convert {legacy_path}: {exc}")
                    return 1

                try:
                    _write_and_verify(data, config_path)
                except OSError as exc:
                    print(f"Unable to write {config_path}: {exc}")
                    return 1
                except Exception as exc:
                    print(f"Wrote {config_path}, but failed to reload it.")
                    print(str(exc))
                    return 1

                try:
                    legacy_path.unlink()
                except OSError as exc:
                    print(f"Converted data, but failed to delete {legacy_path}: {exc}")
                    return 1

                print(f"Converted {legacy_path} to {config_path}.")
                return 0

        if not _confirm_overwrite(config_path):
            return 0

        data = _collect_config_data()

        try:
            _validate_data(data)
        except ValidationError as exc:
            for line in _format_validation_errors(exc):
                print(line)
            return 1
        except ValueError as exc:
            print(str(exc))
            return 1

        try:
            _write_and_verify(data, config_path)
        except OSError as exc:
            print(f"Unable to write {config_path}: {exc}")
            return 1
        except Exception as exc:
            print(f"Wrote {config_path}, but failed to reload it.")
            print(str(exc))
            return 1

        print(f"Configuration written to {config_path}.")
        return 0
    except (EOFError, KeyboardInterrupt):
        print("\nSetup canceled.")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
